[project]
name = "essic-app"
version = "0.1.0"
description = "ESSIC Documenting System"
requires-python = ">=3.9,<3.14"
dependencies = [
    "annotated-types",
    "anyio",
    "appscript",
    "Authlib",
    "blinker",
    "CacheControl",
    "certifi",
    "cffi",
    "charset-normalizer",
    "click",
    "cryptography",
    "diskcache",
    "distro",
    "docx2pdf",
    "dxpdf",
    "et_xmlfile",
    "filelock",
    "firebase-admin",
    "Flask",
    "Flask-SQLAlchemy",
    "fsspec",
    "google-ai-generativelanguage",
    "google-api-core",
    "google-api-python-client",
    "google-auth",
    "google-auth-httplib2",
    "google-cloud-core",
    "google-cloud-firestore",
    "google-cloud-storage",
    "google-crc32c",
    "google-generativeai",
    "google-resumable-media",
    "googleapis-common-protos",
    "groq",
    "grpcio",
    "grpcio-status",
    "h11",
    "hf-xet",
    "httpcore",
    "httplib2",
    "httpx",
    "huggingface_hub",
    "idna",
    "itsdangerous",
    "Jinja2",
    "jiter",
    "joserfc",
    "llama_cpp_python",
    "lxml",
    "MarkupSafe",
    "msal",
    "msgpack",
    "numpy",
    "openai",
    "openpyxl",
    "packaging",
    "pillow",
    "proto-plus",
    "protobuf",
    "psycopg",
    "psycopg-binary",
    "pyasn1",
    "pyasn1_modules",
    "pycparser",
    "pydantic",
    "pydantic_core",
    "PyJWT",
    "pyotp",
    "pyparsing",
    "pypng",
    "python-docx",
    "python-dotenv",
    "PyYAML",
    "qrcode",
    "requests",
    "sniffio",
    "SQLAlchemy",
    "tqdm",
    "typing-inspection",
    "typing_extensions",
    "uritemplate",
    "urllib3",
    "Werkzeug"
]

[tool.vercel]
entrypoint = "app:app"